import { Archive, Download, FileImage, FileSpreadsheet, FileText } from "lucide-react";
import { downloadUrl } from "../../api/analysis";
import type { DownloadCategory, DownloadFile } from "../../types/analysis";
import { fmtBytes } from "../../utils/format";

const GROUPS: { category: DownloadCategory; title: string }[] = [
  { category: "image", title: "Input and smoothed images" },
  { category: "texture", title: "Texture maps (with colour bar)" },
  { category: "cluster", title: "K-Means cluster maps" },
  { category: "figure", title: "Figures" },
  { category: "table", title: "Statistics tables" },
  { category: "text", title: "Interpretation" },
];

function FileIcon({ category }: { category: DownloadCategory }) {
  if (category === "table") return <FileSpreadsheet className="h-3.5 w-3.5 text-slate-400" aria-hidden />;
  if (category === "text") return <FileText className="h-3.5 w-3.5 text-slate-400" aria-hidden />;
  return <FileImage className="h-3.5 w-3.5 text-slate-400" aria-hidden />;
}

export function DownloadPanel({ files, zipUrl }: { files: DownloadFile[]; zipUrl: string }) {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-slate-200 bg-slate-50 px-3 py-2">
        <p className="text-xs text-slate-600">
          {files.length} files generated by the backend for this analysis.
        </p>
        <a
          href={zipUrl}
          className="inline-flex h-8 items-center gap-2 rounded-md bg-teal-700 px-3 text-sm font-medium text-white hover:bg-teal-800"
        >
          <Archive className="h-4 w-4" aria-hidden /> Download all (.zip)
        </a>
      </div>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {GROUPS.map((g) => {
          const items = files.filter((f) => f.category === g.category);
          if (items.length === 0) return null;
          return (
            <div key={g.category}>
              <p className="label-caps mb-1">{g.title}</p>
              <ul className="divide-y divide-slate-100 rounded-md border border-slate-200 bg-white">
                {items.map((f) => (
                  <li key={f.name}>
                    <a
                      href={downloadUrl(f.url)}
                      className="flex items-center gap-2 px-2.5 py-1.5 text-xs hover:bg-slate-50"
                      title={f.name}
                    >
                      <FileIcon category={f.category} />
                      <span className="min-w-0 flex-1 truncate text-slate-800">{f.label}</span>
                      <span className="num shrink-0 text-[11px] text-slate-400">{fmtBytes(f.sizeBytes)}</span>
                      <Download className="h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden />
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>
    </div>
  );
}
